### PR TITLE
Fix broken artist info tab

### PR DESCRIPTION
**Pull request by Atrament666**
Hi guys,
this fixes the broken fetching of artist info which hasn't been working for some time. 

Tested on up-to-date Manjaro Linux.

### CODE REVIEW

**Comment by daddy33** [comment]
Working great. But why has this not been included in the master release so far?

**Comment by hatstand** [comment]
The correct fix is to install a non broken version of QJson on your system.

**Comment by daddy33** [comment]
Thanks a lot for the tip. Now the question is : where to find a non broken version of QJson for Manjaro/Arch?

**Comment by Atrament666** [comment]
> Now the question is : where to find a non broken version of QJson for Manjaro/Arch?

You can clone https://github.com/flavio/qjson and checkout the old 0.8.1 release, build it and install it manually. Building the Clementine with this library really fixes the problem although I am not convinced that many Arch/Manjaro users will be willing to do that :( And I believe that the version 0.9.x will find it's way to the other distributions soon and the problem will affect even more users :(

**Pull request closed without merging**
