### PR TITLE
fix build (Qt5) qtlockedfile_win.cpp

### PR DESCRIPTION
**Pull request by pavelvat**
logs:
https://gist.github.com/pavelvat/53ce11e6b896c8a4a5fbc5c48f1bd2d9 
https://gist.github.com/pavelvat/6cb91b59adbe40e96c3c15063a08dd81

### CODE REVIEW

**Comment by hatstand** [comment]
Can you upstream this?

**Comment by pavelvat** [comment]
PR reworked:
remove unneeded namespace QtLP_Private,
use conversion to WCHAR*, the same how in current master branch:
https://github.com/clementine-player/Clementine/blob/master/3rdparty/qtsingleapplication/qtlockedfile_win.cpp#L68
https://github.com/clementine-player/Clementine/blob/master/3rdparty/qtsingleapplication/qtlockedfile_win.cpp#L76

**Comment by pavelvat** [comment]
https://codereview.qt-project.org/#/c/182662/

**Comment by pavelvat** [comment]
any problems with this PR? Corrections are the same as in the master branch.

**Pull request closed without merging**
