### PR TITLE
PR for Clementine snap

### PR DESCRIPTION
**Pull request by kz6fittycent**
This snap has been published for some time. It's working well, though pretty ugly on non-KDE systems. Perhaps upstream can work on it/fix it. 

Let me know how I can help with the project.

### CODE REVIEW

**Comment by kz6fittycent** [comment]
FYI, I've requested "classic" confinement for the snap; which should increase some of it's capabilities on most Linux distros. It's likely that Canonical will request your input and perhaps that you guys republish the snap under your account. 

Let me know how you'd like to proceed. 

Kind Regards.

**Comment by TheYokai** [comment]
Hope you're still interested in supporting this, because I am as well! I think this could be very good for clementine, especially when it comes to extending the functionality with more gstreamer plugins and options. So far, everything looks good from the yml file -- I'll give it a try on my system (and maybe a VM) to try it out a bit.

Just wanted you to know that I too think this would be cool, and it would be nice to have clementine be on the snap repository.

**Comment by jonaski** [comment]
Remove libechonest and add gstreamer1.0-plugins-alsa

**Comment by kz6fittycent** [comment]
> Remove libechonest and add gstreamer1.0-plugins-alsa

done.

**Comment by hatstand** [comment]
I know nothing about snaps so what's the deal with publishing them? Do we just post this file on the website? Do we build something and post that? Do we need to be in some registry thing? Do we need to sign things?

**Comment by TheYokai** [comment]
> Do we build something and post that? Do we need to be in some registry thing? Do we need to sign things?

@kz6fittycent can probably provide more details on build instructions as I'm not extremely familiar with the process, but you basically need to build a snap by using the `snapcraft.yaml` provided in this patch by running `snapcraft`. This should be all you need to produce a workable snap. 

You will then need to register for a developer account, register an application name, and push the snap to the snapcraft.io website. Unlike repositories or flatpaks, snapcraft.io is the only host for snaps so all snaps are distributed by and through them.

**Comment by kz6fittycent** [comment]
Well, let's backtrack just a little. 

The "easiest" way to get it published and have the update automagically pushed to the store is to register an account on snapcraft.io

The next bit would require some interaction between you (Clementine team) and I to transfer the ownership of the snap to the Clementine Project. This would happen at forum.snapcraft.io

If you already have an account with Ubuntu One or perhaps Launchpad, I believe those same credentials work. 

Let me know if you need any further assistance. 

P.S. The cool thing is that the build service will update your snaps each time you push to your Git repo. It's pretty easy and once the snap is stable (as is the case here), it "just works".

**Pull request merged**
