### PR TITLE
Add keyboard shortcut to delete files from disk, closes #6164

### LINKED ISSUE #6164: DELETE key should perform 'Delete from Disk'
Right now:
- Backspace key performs 'Remove from playlist'
- Delete key performs 'Remove from playlist'

Suggested behavior:
- Backspace key performs 'Remove from playlist' (no change)
**- Delete key should perform 'Delete from Disk'** (changed!)

Additionally, when the 'Delete from disk' action is started, the prompt that appears has two buttons: **Cancel** and **Yes**. I believe **Cancel** should be changed to **No** and a temporary key binding during this prompt should allow a **Y** or **N** key to be pressed to perform either of these actions. This would make deleting files from disk entirely possible with keyboard actions alone -- not requiring a mouse.

### PR DESCRIPTION
**Pull request by wheresvic**
Uses `ctrl+x`

### CODE REVIEW

**Comment by wheresvic** [comment]
@hatstand aha ok fair enough, I will close the PR !

**Comment by G-9999** [comment]
@wheresvic is control+x hard coded or can it be changed? Personally, I'd  love to be able to customize it to a single key, like the DELETE key !

**Comment by wheresvic** [comment]
@G-9999 I had just hardcoded it as you can see from the change `playlist_delete_->setShortcut(QKeySequence("Ctrl+X"));` but you can also simply try using `DELETE ` and see if that works!

**Comment by G-9999** [comment]
@wheresvic love to... but the latest build is
clementine-1.3.1-500-g9eb92ee.dmg                  16-Oct-2018 00:50            39092592
...not sure the frequency of these builds or if they are even automatic?

**Comment by amhndu** [comment]
Can we instead have it as a configurable shortcut but disabled by default ?
If a user explicitly sets a shortcut by themselves, surely they can't blame the player.

**Comment by G-9999** [comment]
Please make this as @amhndu has suggested which is inline with my original request in https://github.com/clementine-player/Clementine/issues/6164 ... being able to bind the delete action to a single key. Having it not set after install also solves the "user stupidity" issue as has been mentioned. I'm personally not happy with Control+X at all 😭

**Comment by G-9999** [comment]
@wheresvic could you perhaps offer some guidance on perhaps re-opening this ticket so that it can track the status of this feature being implemented as a user-configurable key? Myself and @amhndu  would love to have this power and control !!

**Comment by G-9999** [comment]
😢

**Pull request closed without merging**
