### PR TITLE
Fix OAuthenticator reply parsing.

### PR DESCRIPTION
**Pull request by selumin**
Provide QByteArray instead of QIODevice to QJson parser.
Bug link: https://github.com/flavio/qjson/issues/52

### CODE REVIEW

**Comment by selumin** [comment]
Probably will fix #5457

**Comment by hatstand** [comment]
If this really fixes things, then I'd like to know why because we have this pattern everywhere.

**Comment by selumin** [comment]
This pattern is correct, but there is a regression in libqjson, which was introduced between 0.8.1 and 0.9.0 releases (774c7785099be575d3d39fa698c6186919e4521a - break commit if someone is interested).

**Comment by selumin** [comment]
I've updated all problem places in code. It resolves issues with loggin into Google Drive and Dropbox, for example.

**Comment by hatstand** [comment]
We should rely on the upstream fix I think and perhaps check for QJson > 0.9.0 at compile time.

**Comment by selumin** [comment]
@hatstand But clementine use shared version of qjson, so compile time check wouldn't solve the problem. 
Could we temporary add qjson to project's repo as 3rd party and build it as static library? 
When qjson version with fixed behavior will be released, we will drop dependency from repo.

**Comment by hatstand** [comment]
I realise it's not perfect but it's best if we can avoid adding more things to 3rdparty. Perhaps we can add a wrapper function for now that we use everywhere.

The best thing to do would be to harass distros into updating their qjson for the bugfix.

**Comment by abika** [comment]
This bug in QJson also breaks fetching tags from Musicbrainz.
How about using the [JSON support build-in in Qt](http://doc.qt.io/qt-5/json.html)? It came with 5.0 which is 4 years old now. We could remove QJson everywhere.

**Comment by abika** [comment]
Nevermind, Clementine is still using Qt4.

Well, I can help if somebody decides how to solve this (globally).

**Pull request closed without merging**
