### PR TITLE
Fix build: add zlib to deps where it's used 

### PR DESCRIPTION
**Pull request by DarthGandalf**
Ref https://bugs.gentoo.org/887105

### CODE REVIEW

**Comment by hatstand** [comment]
If zlib is only required by Qt5Network then shouldn't this be pulled in via the various Qt5 cmake rules?

**Comment by DarthGandalf** [comment]
https://github.com/clementine-player/Clementine/blob/9ef681b0e9e945c662905c1ffc5e179dd8e04d3c/3rdparty/qtiocompressor/qtiocompressor.cpp#L48 requires it too

**Comment by hatstand** [comment]
> https://github.com/clementine-player/Clementine/blob/9ef681b0e9e945c662905c1ffc5e179dd8e04d3c/3rdparty/qtiocompressor/qtiocompressor.cpp#L48
> 
> requires it too

I think adding `z` to the `target_link_libraries()` in that directory's `CMakeLists.txt` would fix that. It's better than doing it globally as it should take care of the ordering too I think.

**Comment by DarthGandalf** [comment]
Yes, I agree, that's cleaner. Done.

**Pull request merged**
