### PR TITLE
include opus support in windows build

### PR DESCRIPTION
**Pull request by fireandfuel**
See issue #5189 

DLL files for the opus support are already done for the windows build in the repository clementine-player/Depedencies (master branch). 

This pull request simply added them to the NSI package and registers .opus files (which are basically ogg containers) to clementine.

### CODE REVIEW

**Comment by myfreeweb** [comment]
This was reverted and still not added back?! :(

**Comment by fireandfuel** [comment]
@myfreeweb I'm not sure whether the dependencies will be rebuilded by the clementine build system on every push to the repositories master branch or not, the master branch at https://github.com/clementine-player/Dependencies is broken for windows see https://github.com/clementine-player/Dependencies/issues/10

**Comment by hatstand** [comment]
Please send another pull request if you want it merged again

**Comment by bb010g** [comment]
@fireandfuel Are you planning on submitting a new PR, or should someone else submit a fixed one?

**Comment by fireandfuel** [comment]
@bb010g I can't test the build on my local machine (it wouldn't compile because of Clementine's dependencies broken), so I DO NOT submit a new PR.

**Comment by crlorentzen** [comment]
Tried the latest build available https://builds.clementine-player.org/win32/release/ClementineSetup-1.3.1-388-gf1b767f.exe and still not working. Do we have a timeline to a release with opus re-integrated?

**Comment by gappleto97** [comment]
It would be nice if we could get a response on this.

**Comment by fireandfuel** [comment]
@crlorentzen @gappleto97 I'm sorry, I'm not interested in Clementine any longer. If you want Opus playback on Windows, like Clementine, check out foobar2000.

**Comment by JulianVolodia** [comment]
Hey @crlorentzen @gappleto97 @myfreeweb @bb010g , long time no see.

Could you tell me about issue? I will not check until new releases will be there but there is going out there.

What I could see now I could see rolling build on CircleCI includes needed libs.

'/target/bin/libopus-0.dll' -> 'clementine-deps/libopus-0.dll'
'/target/lib/gstreamer-1.0/libgstopus.dll' -> 'clementine-deps/gstreamer-plugins/libgstopus.dll'

If you want to return here and talk with us feel free to be here. We are doing big changes to build system to be more friendly with rolling release as changes appear in repository so please consider testing in Advent of Code ;)

Happy Hacking friends.

PS if I see correctly at most only Registerextension and mediatype need to declared.

**Pull request merged**
