### PR TITLE
protobuf: Fix namespace conflict

### LINKED ISSUE #6926: Use of pb namespace incompatible with protobuf 3.15.0
The new protobuf 3.15.0 seems to add a new `pb` namespace alias that breaks compilation of clementine. Replacing the `pb` namespace with `cpb` allows clementine to compile. A sample patch is available at https://github.com/ahesford/void-packages/blob/protobuf/srcpkgs/clementine/patches/pb_namespace.patch

The patch applies cleanly to 1.4.0rc1 but I am not sure about the head of `master`.

### PR DESCRIPTION
**Pull request by jbroadus**
Protobuf 3.15 adds a namespace alias for "pb" that conflicts with
Clementine's. Modify Clementine to use "cpb".

Patch provided by @ahesford

Reference: https://github.com/protocolbuffers/protobuf/blob/5c028d6cf42e426d47f5baa6ea3f0f5c86b97beb/src/google/protobuf/port.h#L44

Fixes #6926

### CODE REVIEW

**Comment by jbroadus** [comment]
@mbruel  Will this require changes to the remote as well?

**Comment by hatstand** [comment]
> @mbruel Will this require changes to the remote as well?

I don't think it will as that has its own copy of the protos and specifies `java_package` anyway.

**Comment by jbroadus** [comment]
Fixed the formatting issues.

**Comment by mbruel** [comment]
@jbroadus what's the conflict exactly?
The `pb::remote` namespace is still available right?

**Pull request merged**
