### PR TITLE
Add liblastfm to brew dependencies.

### PR DESCRIPTION
**Pull request by jbroadus**
Making a guess here.

### CODE REVIEW

**Comment by jbroadus** [comment]
I don't see mac builds in the CI/CD list. Are they built separately?

**Comment by jbroadus** [comment]
Oh, I see.
37742e2bbd Only build mac on `master` due build time limits

**Comment by jbroadus** [comment]
I tried setting up circle-ci, but it looks like mac builds aren't available in the base package.

**Comment by hatstand** [comment]
I don't think this exists in brew. You can use Tomahawk's though from `https://raw.githubusercontent.com/tomahawk-player/homebrew-tomahawkqt5/master/liblastfm.rb`

**Comment by jonaski** [comment]
Its called just lastfm: https://formulae.brew.sh/cask/lastfm

**Comment by hatstand** [comment]
That's not the library, that's the _app_.

**Comment by jbroadus** [comment]
I'll have to leave this one to somebody with a Mac.

**Pull request closed without merging**
