### PR TITLE
Fix a number of zero-value tag issues

### PR DESCRIPTION
**Pull request by smithjd15**
Some fixes to prevent the writing of zero values and also addressing the inability to clear some tag fields in the tag editor.

- Fix compilation and disc field zero-value checks
- Check year, track and statistics fields for zero-values

### CODE REVIEW

**Comment by smithjd15** [comment]
Fixes (or improves): #1835 #3711 #3528

**Comment by smithjd15** [comment]
Can this be improved/changed for re-consideration?

**Comment by hatstand** [comment]
It failed the checks.

**Comment by smithjd15** [comment]
Can you re-open this? I've pushed a formatting change.

**Comment by hatstand** [comment]
Can you open a new one?

**Pull request closed without merging**
