### PR TITLE
Clementine Menu bar hide by default (user modifiable preference - ALT key press unhide)

### PR DESCRIPTION
**Pull request by narunlifescience**
Clementine menubar is rarely used by users as most of the options in the menu bar are layed out on the application main window itself.  this modification hides menu bar by default (user modifiable preference via preferences/appearance menu). pressing alt key unhides the menubar. (similar to Mozilla firefox menubar)

### CODE REVIEW

**Comment by amuttsch** [comment]
Hm, I don't like the trend with the hidden menu bar. With this PR, users don't have an indication that the menu bar can be shown with the `alt` key. They might think it's gone completely.

**Comment by Tatsh** [comment]
No thanks. You can definitely add the feature to hide the menu bar as all KDE apps have that built-in with Ctrl+M but it should not be hidden by default. This is not a Windows Vista+ app (like Explorer or WMP).

**Comment by narunlifescience** [comment]
Modifying UI is always controversial! This code can also be modified so that user can enable or disable this feature by using an entry in preferences and settings (some thing like a checkbox). @Tatsh > I am very much aware that this is a cross platform app (I use arch + xfce). This is not a KDE app either (There are tons of desktop environments out there).

**Comment by Tatsh** [comment]
I can yell too.

You are correct! You know why?! Clementine is based on Amarok 1.4! Stop trying to make it into Amarok 2!

**Comment by Ferroin** [comment]
I agree with narunlifescience, this should be a user modifiable preference.

**Comment by narunlifescience** [comment]
modified the code as a user selectable preference.

**Comment by Tatsh** [comment]
I have a sort of feeling that Linux should not necessarily get the Alt key treatment. It makes sense on Windows because Windows has this behaviour in applications like Explorer, IE, and WMP.

In KDE Ctrl+M toggles the menu in most applications. I do not really want to see detection of DE in Clementine code really but Firefox does do this. They use Alt key on KDE and F10 on GNOME. Not sure why F10. Firefox probably does a check with environment, `XDG_CURRENT_DESKTOP` (a Freedesktop standard). No real consistency anywhere (like I said most KDE applications use Ctrl+M), so I do not care that much.

One big thing: have you considered what is going to happen in OS X? Perhaps you should completely disable this feature there (`#ifndef Q_OS_OSX`).

**Comment by narunlifescience** [comment]
Thank you for pointing out the mac issue. may have to find a work around; some thing similar to what you pointed out.
Don't you think that removing menu bar would give clementine a cleaner look and little more screen-space? especially in small form factor gadgets (laptops,netbooks etc)? (Well, it is debatable I guess)

Although I am not perticular about using alt key, I don’t see any better choice.  Also, I don’t want to make some weired key combination. I thought that ALT key would be easy for users as most of the users irrespective of the operating system would be familiar with ALT key usage in firefox. 

Even in KDE, this code should not make any issues (although i did not test it in KDE). both Ctrl+M and ALT should work (even menu bar hidden by Ctrl+M should unhide with alt key press and vise versa).

**Comment by ArnaudBienner** [comment]
Thanks for the effort you put in this pull request.
However, I don't really like the idea.
In Firefox, options are still available through the menu in the right, so even if the menu bar isn't visible, all the options are still accessible to the users. Good point it will be an option and activated by default, otherwise I would have been definitely against this (but still, some user might turn on this option accidentally, and don't figure out how set turn if off).
Also, in Firefox, this makes sense: to make web browsing more comfortable, it makes sense to save as much space as possible. In Clementine, IMHO, the advantage of this is less obvious: Clementine is used to listen to music, not to watch some content, so saving space isn't as critical. All the contrary actually: I believe it's better to most of the options instantly visible to the user, so he can easily access them.

**Comment by narunlifescience** [comment]
Hmm.. I don’t want to trouble users by adding a feature. If most of you guys feel that it should not be added then may be you are right.

**Pull request closed without merging**
