### PR TITLE
Updated qt bug report page

### PR DESCRIPTION
**Pull request by mananaBanana**
The original bug report page in the comments ([this link](https://bugreports.qt-project.org/browse/QTBUG-32789)) is unreachable.

### CODE REVIEW

**Comment by hatstand** [comment]
Please revert the translations and do them on transifex instead, otherwise they will be overwritten.

**Comment by mananaBanana** [comment]
Done! Will add them later on transifex. I thought that this file cannot be updated using transifex (according to #5845). Was that fixed?

**Comment by hatstand** [comment]
Oh, you're right, sorry! It would still be better as a separate pull request though.

**Comment by mananaBanana** [comment]
Kein Problem! Will do so. I'll have to push to a new branch, right?

**Comment by hatstand** [comment]
Manually merged in: https://github.com/clementine-player/Clementine/compare/c024b1340d6d...ba8a82bffab4

**Pull request closed without merging**
