### PR TITLE
Updated to implement the feature request asking for a file containing… 

### PR DESCRIPTION
**Pull request by MelissaManley97**
…play count information to be made for Spotify songs. This feature will add a file to the user's home directory (upon playing their first Spotify song) named "SpotifyPlayCount.csv." This file contains each song's title, artist, year, and play count. Please consider adding this feature.

Thank you,
Melissa Manley

>[https://github.com/Team-NullPointer/Clementine/issues/6](https://github.com/Team-NullPointer/Clementine/issues/6l)

### CODE REVIEW

**Comment by hatstand** [comment]
I don't see why we would spam a user's home directory with this?

**Comment by HighMans** [comment]
Added option to disable as well as an option to choose output location.

**Comment by HighMans** [comment]
We've added an option to disable it, as well as an option to choose for the output directory. Please review.

**Comment by HighMans** [comment]
Hello again Hatstand, I was wondering if you had a change to review this PR?

**Comment by hatstand** [comment]
I'm still not a fan of this feature. I'd much prefer something that more generally supports play counts across non-local files and it makes more sense to use the database for that and make CSV output a separate feature afterwards.

**Pull request closed without merging**
