### PR TITLE
build: Add Mac Mojave build

### PR DESCRIPTION
**Pull request by jbroadus**
Fix for #6922

### CODE REVIEW

**Comment by hatstand** [comment]
Mojave builds should work on Catalina so it's good to build for both but I don't think we need to ship artifacts for both.

**Comment by jbroadus** [comment]
Okay, I updated the existing mac build. Do you have a Catalina machine that you can test this on?

**Comment by hatstand** [comment]
I can test on Catalina if you can link me to a DMG.

**Comment by jbroadus** [comment]
> I can test on Catalina if you can link me to a DMG.

https://github.com/clementine-player/Clementine/suites/2056479897/artifacts/41477598

**Comment by hatstand** [comment]
> > I can test on Catalina if you can link me to a DMG.
> 
> https://github.com/clementine-player/Clementine/suites/2056479897/artifacts/41477598

That works on Catalina 10.15.7 👍

**Pull request merged**
