### PR TITLE
Require Qt4.8.6 and CMake deprecate warnings

### PR DESCRIPTION
**Pull request by JulianVolodia**
"com.trolltech.*" changed to "org.qtproject.*"

### CODE REVIEW

**Comment by hatstand** [comment]
Ubuntu Precise is still on 4.8.1

**Comment by JulianVolodia** [comment]
@hatstand, we could leave there 4.8.1 and fix that deprecation, what you think?

**Comment by hatstand** [comment]
I think 4.8.1 would be fine

**Comment by JulianVolodia** [comment]
Merged #5287 .

**Pull request closed without merging**
