### PR TITLE
make library view sort line themable

### PR DESCRIPTION
**Pull request by narunlifescience**
untitled

@ArnaudBienner could you please check if the alpha level is ok ? or should i tweak the value ?

### CODE REVIEW

**Comment by ArnaudBienner** [comment]
An alpha value of 100 looks more like what we previously had.
So if 100 is good for you, maybe we can use that? I feel like line looks too "strong" with a 200 alpha value, and we don't need to have it so visible. Or maybe something in between; as you prefer :)

**Comment by narunlifescience** [comment]
alpha value of 100 looks fine

untitled

**Comment by narunlifescience** [comment]
Done!

**Comment by ArnaudBienner** [comment]
Thanks for the patch :)

**Pull request merged**
