### PR TITLE
Specify cpp11 compatibility Fix #6199

### LINKED ISSUE #6199: Build fails on the qt5 branch
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: *macOS 10.13*
- Clementine version: la

### Description of my problem

I'm unable to build the latest `qt5` branch. Here is my build log: https://pastebin.com/ST49ZfGP

I opened an issue as requested here: https://github.com/clementine-player/Clementine/issues/3463#issuecomment-437172661

### PR DESCRIPTION
**Pull request by MartinDelille**
I specified C++ 11 compatibility as adviced here: https://github.com/clementine-player/Clementine/issues/6199#issuecomment-443002387

### CODE REVIEW

**Comment by hatstand** [comment]
Can you move this to just the module that requires it?

**Comment by MartinDelille** [comment]
@hatstand I'm not so good with `cmake` so let me just explain the problem:

When following the build procedure, `make` is failing: https://github.com/clementine-player/Clementine/issues/6199#issuecomment-442406573

I add the following lines to the main `CMakeList.txt` file:

```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --std=c++0x")
```

I'm not sure to identify which modules requires it regarding the log. Since `protobuf` is used in the `src` folder I suppose I had to add it there but it is already the case: https://github.com/clementine-player/Clementine/blob/c9ff5a6f13ab6403eaa6a40f9e57701f0f7703e9/src/CMakeLists.txt#L3

Any tips how to identify the necessary module?

Or maybe you can explain me why not add it globally to the project?

**Comment by jonaski** [comment]
@MartinDelille 
Put it in https://github.com/clementine-player/Clementine/blob/master/ext/libclementine-remote/CMakeLists.txt instead.
Like it's already done in https://github.com/clementine-player/Clementine/blob/master/ext/libclementine-tagreader/CMakeLists.txt

**Comment by MartinDelille** [comment]
@jonaski Done

**Pull request merged**
