### PR TITLE
all required changes for ClemRemote v1.0 (sum of my 5 previous PR)

### PR DESCRIPTION
**Pull request by mbruel**
Hi,

I've released [ClemRemote v1.0](https://github.com/mbruel/ClementineRemote).
I built it for Desktops, and started the process to get it on Android and Apple Stores.
It's working with the current version of Clementine (v1.3.1) but many new handy features won't.
I've built [Clementine v1.4.0rc1ClemRemote](https://github.com/mbruel/Clementine/releases/tag/1.4.0rc1ClemRemote) from those changes in case you wish to test it.

I hope to hear from you guys, that you'll merge my work (I'm open to review and changes if needed) and most of all that you'll publish soon the v1.4.
I'd be happy to have my Remote within clemetine-player main [GitHub](https://github.com/clementine-player).
Once I get ClemRemote published on Android and Apple, it would be great to add their QR codes in the Network Remote settings.

Have a good day,
Matthieu

### CODE REVIEW

**Comment by hatstand** [comment]
Can you rebase this as it conflicts with `master`?

**Comment by mbruel** [comment]
@hatstand done

**Comment by hatstand** [comment]
This still conflicts with `master`. Use `git fetch && git rebase origin/master` to fix it.

**Comment by mbruel** [comment]
that's what I just did and I resolved all conflicts by hand keeping what was needed...
`git fetch && git rebase origin/master` gives me `Current branch master is up to date.`
I've done `git rebase upstream/master`
redoing it would bring me to the same point. I'm not sure what I can do...

**Comment by hatstand** [comment]
Did you push it?

**Comment by mbruel** [comment]
yep it was this change https://github.com/clementine-player/Clementine/pull/6842/files

**Comment by mbruel** [comment]
closing this one as #6845 is rebased

**Pull request closed without merging**
